name: Coveralls 

on:
  push:
    branches: [ BackEnd ]
  pull_request:
    branches: [ BackEnd ]

jobs:
  coveralls:

    runs-on: ubuntu-latest
    

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
    # BACKEND
    - name: Use Node.js 18.x 
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - name: Install dependencies
      working-directory: ./
      run: npm install
    - name: Generating coverage information
      run: npm run coveralls
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/server/coverage/lcov.info
        base-path: ./
